version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - vc-node-app  

  vc-node-app:
    build: .
    image: vickysomtee/vc-node-app
    environment:
      - PORT=3000  
    depends_on:
      - mongo  

  mongo:
    image: mongo:4.4.10
    volumes:
      - mongo-db:/data/db 
    ports:
      - "27018:27017"  
      
volumes:
  mongo-db:      
          