version: "3"
services:
  nginx:
    ports:
      - "3000:80"
      
  vc-node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=vickysomtee
      - MONGO_PASSWORD=victor32
      - JWT_SECRET=secretkey
    command: npm run dev  

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=vickysomtee
      - MONGO_INITDB_ROOT_PASSWORD=victor32